from tc_messageBroker.rabbit_mq.event import Event


def test_enum_event_default():
    # For now we have the events below
    assert Event.SERVER_API.UPDATE_GUILD == "UPDATE_GUILD"
    assert Event.DISCORD_BOT.FETCH == "FETCH"
    assert Event.DISCORD_BOT.SEND_MESSAGE == "SEND_MESSAGE"
    assert Event.DISCORD_ANALYZER.RUN == "RUN"
    assert Event.DISCORD_ANALYZER.RUN_ONCE == "RUN_ONCE"
    assert Event.DISCORD_BOT.FETCH_MEMBERS == "FETCH_MEMBERS"
    assert (
        Event.DISCORD_BOT.INTERACTION_RESPONSE.CREATE == "INTERACTION_RESPONSE_CREATE"
    )
    assert Event.DISCORD_BOT.INTERACTION_RESPONSE.EDIT == "INTERACTION_RESPONSE_EDIT"
    assert (
        Event.DISCORD_BOT.INTERACTION_RESPONSE.DELETE == "INTERACTION_RESPONSE_DELETE"
    )
    assert Event.DISCORD_BOT.FOLLOWUP_MESSAGE.CREATE == "FOLLOWUP_CREATE"
    assert Event.TWITTER_ANALYZER.RUN == "RUN"
    assert Event.TWITTER_BOT.EXTRACT.PROFILES == "EXTRACT_PROFILES"
    assert Event.TWITTER_BOT.EXTRACT.LIKES == "EXTRACT_LIKES"
    assert Event.TWITTER_BOT.EXTRACT.TWEETS == "EXTRACT_TWEETS"
    assert Event.TWITTER_BOT.SEND_MESSAGE == "SEND_MESSAGE"
    assert Event.HIVEMIND.INTERACTION_CREATED == "INTERACTION_CREATED"
    assert Event.HIVEMIND.GUILD_MESSAGES_UPDATED == "GUILD_MESSAGES_UPDATED"
    # assert Event.DISCORD_ANALYZER.SAVE == "SAVE"
