name: Build & Test

on:
  pull_request:
    types: [opened, synchronize,reopened]
    
jobs:
  ci:
    uses: TogetherCrew/operations/.github/workflows/ci.yml@main
    secrets:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}