class Queue:
    SERVER_API = "SERVER_API"
    DISCORD_BOT = "DISCORD_BOT"
    DISCORD_ANALYZER = "DISCORD_ANALYZER"
    TWITTER_BOT = "TWITTER_BOT"
    TWITTER_ANALYZER = "TWITTER_ANALYZER"
    HIVEMIND = "HIVEMIND"
